name: 🤖 AI Code Review
on:
  push:
    branches:
      - main  # o la rama que prefieras


jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: GenAI Code Review
        uses: cirolini/genai-code-review@v2
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token:   ${{ secrets.GITHUB_TOKEN }}
          github_pr_id:   ${{ github.event.pull_request.number }}
          # Opcionales:
          # openai_model:        "gpt-4o-mini"
          # openai_temperature:  0.2
          # mode:                "patch"   # o "files"
